name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'  # Match the Ruby version to your local development environment
          bundler-cache: false # Turn off automatic Bundler caching

      - name: Install specific Bundler version
        run: gem install bundler -v '2.5.9'

      - name: Install Gems
        run: |
          bundle _2.5.9_ install

      - name: Build the site with Jekyll
        run: |
          bundle _2.5.9_ exec jekyll build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
